
import logo1 from '../assets/images/google.png'
import logo2 from '../assets/images/netflix-4 1.png'
import logo3 from '../assets/images/tesla-9 1.png'
const jobListings = [
  {
    id: 1,
    logo: logo1,
    title: 'Senior Software Engineerr',
    company: 'Tech Innovators Inc.',
    location: 'San Francisco, CA',
    salary: '$120,000 - $150,000',
    jobDescription: 'Join our dynamic team as a Senior Software Engineer and play a key role in developing innovative software solutions. Be part of cutting-edge projects that push the boundaries of technology.',
    jobResponsibilities: 'Lead the development of complex software systems, collaborate with cross-functional teams, and mentor junior developers. Ensure code quality, performance, and adherence to best practices.',
    fullAddress: '123 Tech Street, San Francisco, CA 12345',
    experience: '5+ years',
    educationalRequirements: 'Bachelor\'s degree in Computer Science or related field',
    phoneNumber: '+1 (123) 456-7890',
    email: 'seniorengineer@example.com',
  },
  {
    id: 2,
    logo: logo2,
    title: 'Product Manager',
    company: 'Global Tech Solutions',
    remote: false,
    location: 'New York, NY',
    salary: '$110,000 - $140,000',
    jobDescription: 'Exciting opportunity for a product manager to drive innovative solutions in a global tech environment.',
    jobResponsibilities: 'Define product strategy, work closely with development teams, and ensure successful product launches.',
    fullAddress: '456 Tech Avenue, New York, NY 67890',
    experience: '7+ years',
    educationalRequirements: 'Bachelor\'s degree in Business Administration or related field',
    phoneNumber: '+1 (234) 567-8901',
    email: 'productmanager@example.com',
  },
  {
    id: 3,
    logo: logo3,
    title: 'Data Scientist',
    company: 'Infinite Data Insights',
    remote: true,
    location: 'Seattle, WA',
    salary: '$130,000 - $160,000',
    jobDescription: 'Exciting opportunity for a data scientist to analyze and interpret complex data sets.',
    jobResponsibilities: 'Develop statistical models, collaborate with data engineering teams, and communicate insights to stakeholders.',
    fullAddress: '789 Data Lane, Seattle, WA 34567',
    experience: '4+ years',
    educationalRequirements: 'Master\'s degree in Data Science or related field',
    phoneNumber: '+1 (345) 678-9012',
    email: 'datascientist@example.com',
  },
  {
    id: 4,
    logo: logo1,
    title: 'UX/UI Designer',
    company: 'Creative Minds Co.',
    remote: false,
    location: 'Los Angeles, CA',
    salary: '$100,000 - $130,000',
    jobDescription: 'Exciting opportunity for a creative UX/UI designer to shape user experiences for innovative projects.',
    jobResponsibilities: 'Create wireframes, design mockups, and collaborate with development teams to implement intuitive interfaces.',
    fullAddress: '101 Design Lane, Los Angeles, CA 56789',
    experience: '3+ years',
    educationalRequirements: 'Bachelor\'s degree in Design or related field',
    phoneNumber: '+1 (456) 789-0123',
    email: 'designer@example.com',
  },
  {
    id: 5,
    logo: logo3,
    title: 'Senior Frontend Developer',
    company: 'Digital Titans Ltd.',
    remote: true,
    location: 'Austin, TX',
    salary: '$115,000 - $145,000',
    jobDescription: 'Exciting opportunity for a senior frontend developer to build responsive and visually appealing web applications.',
    jobResponsibilities: 'Collaborate with UX/UI designers, optimize web applications for performance, and troubleshoot issues.',
    fullAddress: '567 Code Street, Austin, TX 78901',
    experience: '6+ years',
    educationalRequirements: 'Bachelor\'s degree in Computer Science or related field',
    phoneNumber: '+1 (567) 890-1234',
    email: 'frontenddeveloper@example.com',
  },
  {
    id: 6,
    logo: logo3,
    title: 'Marketing Manager',
    company: 'Strategic Solutions Group',
    remote: false,
    location: 'Chicago, IL',
    salary: '$90,000 - $120,000',
    jobDescription: 'Exciting opportunity for a marketing manager to develop and execute strategic marketing initiatives.',
    jobResponsibilities: 'Create marketing campaigns, analyze market trends, and collaborate with cross-functional teams.',
    fullAddress: '789 Marketing Lane, Chicago, IL 90123',
    experience: '5+ years',
    educationalRequirements: 'Bachelor\'s degree in Marketing or related field',
    phoneNumber: '+1 (678) 901-2345',
    email: 'marketingmanager@example.com',
  },
];

  

  export default jobListings;