const jobCategories = [
    { id:1,
      icon: '💼',
      title: 'Account & Finance',
      jobCount: '300 Jobs Available',
    },
    { id:1,
      icon: '🛠️',
      title: 'Engineering',
      jobCount: '250 Jobs Available',
    },
    { id:1,
      icon: '🎨',
      title: 'Design & Creative',
      jobCount: '180 Jobs Available',
    },
    { id:1,
      icon: '📈',
      title: 'Marketing',
      jobCount: '200 Jobs Available',
    },
    { id:1,
      icon: '💻',
      title: 'Information Technology',
      jobCount: '350 Jobs Available',
    },
    { id:1,
      icon: '🌐',
      title: 'Web Development',
      jobCount: '280 Jobs Available',
    },
    { id:1,
      icon: '🌍',
      title: 'International Relations',
      jobCount: '150 Jobs Available',
    },
    { id:1,
      icon: '🔍',
      title: 'Research & Development',
      jobCount: '220 Jobs Available',
    },
  ];


  export default jobCategories;